project_name: absolutelist
archives:
  - builds:
    - absolutelist
    format: binary
changelog:
  skip: true
release:
  prerelease: auto
builds:
  - id: "absolutelist"
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
      - arm